### Limpieza de Datos

In [1]:
import pandas as pd

In [17]:
data = pd.read_csv('spotify_dataset.csv')

data

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,...,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,...,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,...,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,...,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,...,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

### PASO 1: Eliminación de columnas irrelevantes

Eliminamos 'Unnamed: 0' ya que es un índice duplicado que no aporta información.

In [18]:
df = data.drop(columns=['Unnamed: 0'])

df

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,5,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,0,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,0,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,7,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,1,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

### PASO 2: Tratamiento de valores nulos

Como vimos que solo hay 1 fila con nulos en artistas, álbum y canción, 
la eliminamos directamente ya que representa una pérdida insignificante.

In [19]:
df = df.dropna(subset=['artists', 'album_name', 'track_name'])

df

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,5,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,0,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,0,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,7,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,1,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

Comprobación de celdas vacías (strings vacíos, no nulos).

isnull() no detecta '' ni ' ' : buscamos esos casos aparte.

In [9]:
# Obtener todas las columnas del DataFrame para la comprobación

all_columns = df.columns

print('Celdas con string vacío o solo espacios por columna (todas las columnas):')
for col in all_columns:
    # Se convierte a string para asegurar que str.strip() funcione en todos los tipos de datos
    n = (df[col].astype(str).str.strip() == '').sum()
    if n > 0:
        print(f'  ⚠ {col}: {n} celdas vacías')
        # Mostrar las primeras filas donde se encuentren estos casos
        display(df[df[col].astype(str).str.strip() == ''][[col]].head())
    else:
        print(f'  ✓ {col}: sin celdas vacías')

Celdas con string vacío o solo espacios por columna (todas las columnas):
  ✓ track_id: sin celdas vacías
  ✓ artists: sin celdas vacías
  ✓ album_name: sin celdas vacías
  ✓ track_name: sin celdas vacías
  ✓ popularity: sin celdas vacías
  ✓ duration_ms: sin celdas vacías
  ✓ explicit: sin celdas vacías
  ✓ danceability: sin celdas vacías
  ✓ energy: sin celdas vacías
  ✓ key: sin celdas vacías
  ✓ loudness: sin celdas vacías
  ✓ mode: sin celdas vacías
  ✓ speechiness: sin celdas vacías
  ✓ acousticness: sin celdas vacías
  ✓ instrumentalness: sin celdas vacías
  ✓ liveness: sin celdas vacías
  ✓ valence: sin celdas vacías
  ✓ tempo: sin celdas vacías
  ✓ time_signature: sin celdas vacías
  ✓ track_genre: sin celdas vacías

Limpiar espacios al inicio y al final en columnas de texto.

str.strip() elimina espacios invisibles que pueden causar errores en agrupaciones

In [11]:
for col in ['artists', 'album_name', 'track_name']:
    df.loc[:, col] = df[col].str.strip()
    print(f'  ✓ {col}: espacios limpiados')

  ✓ artists: espacios limpiados
  ✓ album_name: espacios limpiados
  ✓ track_name: espacios limpiados

### PASO 3: Tratamiento de valores duplicados

In [13]:
pd.DataFrame(df['track_id']).groupby('track_id').agg('count')

Empty DataFrame
Columns: []
Index: [0000vdREvCVMxbQTkS888c, 000CC8EParg64OmTxVnZ0p, 000Iz0K615UepwSJ5z2RE5, 000RDCYioLteXcutOjeweY, 000qpdoc97IMTBvF8gwcpy, 0017XiMkqbTfF2AUOzlhj6, 001APMDOl3qtx1526T11n1, 001YQlnDSduXd5LgBd66gT, 001pyq8FLNSL1C8orNLI0b, 002qpSULhHAw6DGqFxbaO1, 002uYDBLOvJz21C4FuArDS, 003lo4y8gOylAqDs2scLx2, 003vvx7Niy0yvhvHt4a68B, 004G9E3EZhxxn5aE9yEQqx, 004h8smbIoAkUNDJvVKwkG, 004iWPkSRbvOEvAPLWHl9M, 0051nJ5xbRu8kuqPTYa9l7, 005NLlv3rClEVqeoSyYTHU, 005U5ZHLoA4OEkWewAa32S, 0068lzo1xXa9ED8ThypHU1, 006ATYzgynEKIPgVaT5LQM, 006Bi4j0yzwOc3y69GOlYV, 006c9li2Mybyg5vm6doEfO, 006rHBBNLJMpQs8fRC2GDe, 006tmNZLXEXPqdb23wwSN1, 0072MKNpMeJNx8aRfTNfQW, 007NMTR9MQrqwCmbjNSjKj, 007t1Fel5tcxHOEfSYWuGM, 007ufdfvS8NxnwuwSkOdw4, 0084XCqFNqZ5K8DliXVSXh, 008KWijTsFnZRK3E7oGNxl, 00970cTs7LnxWt0d5Qk08m, 009DZE5shRgOEnMD47h9uW, 009MGoCC568mI1yvsbmTxw, 00At7PWydsvg7g5xgaYan9, 00B7SBwrjbycLMOgAmeIU8, 00BHbc5GB5d35gsi8IsmZl, 00BWHAHghYsZzxfqS6P9vg, 00BYitnjj9tACCkLapk5uS, 00BxnRDndJwA67Rvi7iqUC, 00C0DktT4pif6k7pVghYuI, 00C93bsNIjHStKvr1lPJee, 00CAvtdfEEtWRkEN6Km2AW, 00CKqQSBhAr2gePvyIzk0P, 00Coyxt9mTec1acC52qtWa, 00CsDW3I9XueUvaXnAvGMm, 00DuOxungwHwVUX2m37P0P, 00EAiVX99rZ4rlYFLItPcC, 00EAqLJcJP8IAzOmJ9q5g8, 00EFWaqXnHZ5smJNsHtnGV, 00EqiscplImrxqlRb4VMsZ, 00EsQxsJv6vy7hEQN3jZWG, 00FDHurakzVEiPutdUxXXq, 00GRoWhqbLHfqOpfsx4pli, 00GVRTIWMjYwwHEjTLclgf, 00I41xsW6SunZDJ5fB8KAd, 00IXrawIDidTg6RrN3pt6X, 00IiTu5o9IVasXMX3udpZo, 00IjIaUaMCFG5gPE4PrDdG, 00IkpLspkS5EvJkp2EyWhR, 00J8yszzb5PR6ZIvSBtg0Y, 00JZ83w0Qm09f4PwWj06sM, 00K3yuFVb33hBNoEyWcdnj, 00KPxBKmSKv26ComPaEZe8, 00KSN0qtGSeYX9qFClCEcg, 00KfIFi2TpAaQGPbRbFbKJ, 00L0P49dBUYKHaeCZF5Q9i, 00L5VK0Etex3Kolo7iglIV, 00LmM2QLGpfb5NC7PC7qqZ, 00LvoGJplEaTcFLC0wIrQ9, 00MVmhRLK69vu0qCcgsM60, 00Mk0LnP5u2W5yJmJpG4va, 00MylqWGNqrD31c1k1lxM4, 00MzADTo5mKZHI0crdQ84L, 00NXXGqY8X8nkHZgxGEEJP, 00NZcRjpixxnyUwltRhj7V, 00NenVXc1ciWotMBpgGiQz, 00Nsyeo2kcU4602zMsLWXW, 00NxqOPo7bEF9QFNU4bJj8, 00OHXqfI4QQN25lbIipmaZ, 00OOn0q7Zudq4VHJYkLbUJ, 00Ofee5Bbfstz49RfSL0oM, 00PBSElFPJbnIcFS7orAm2, 00PHHvUVQ1fbkJbD3Tx5gM, 00PXj8pxWLJ3apEnCPJTNI, 00PnFrg2QQzPqkeuxGxcz9, 00QBHaaP4KUcjlmxWriMbC, 00QgsZma0GDCL0BPj8chP6, 00REsurT9T9JF6CxhT4h39, 00RLfhwjN0Sg4hIkzZ7X7l, 00RTPYo7pvEqHGOyLZWyJu, 00Rptyyrh7YXjPwjd7SAsV, 00RrOc0e6AlGWXRd9FERYR, 00SS0GOzQ6A1zxBvtblkWr, 00TFDHSe7s8cWm5CzDY8UP, 00UJgymLK9v1sGxEMTz5wl, 00UZySJXRYQgnOrlzluIIm, 00UoBmyOfYNPbiQUKWu07R, 00Vp4bBQAZ1s9KEIw5MjgQ, 00VxUWUIKIY3DphqHzZjK5, ...]

[89740 rows x 0 columns]

Investigar duplicados por track_id: cuáles son y por qué. No basta con contarlos, miramos un caso concreto para entender la causa.

In [12]:
repeticiones = df.groupby('track_id').size().reset_index(name='veces')
repetidos = repeticiones[repeticiones['veces'] > 1].sort_values('veces', ascending=False)

print(f'track_id que aparecen más de 1 vez: {len(repetidos)}')
print('\nDistribución de repeticiones:')
display(repeticiones['veces'].value_counts().rename_axis('apariciones').reset_index(name='nº de tracks'))

# Caso concreto con más repeticiones
if not repetidos.empty:
    ejemplo_id = repetidos.iloc[0]['track_id']
    n_veces = repetidos.iloc[0]['veces']
    print(f"\nEjemplo — track_id '{ejemplo_id}' aparece {n_veces} veces:")
    display(df[df['track_id'] == ejemplo_id][['track_id', 'track_name', 'artists', 'track_genre', 'popularity']])
    print('\n→ Conclusión: la misma canción aparece una vez por cada género en el que')
    print('  está clasificada en Spotify. Es la estructura del dataset, no un error.')
else:
    print('\nNo hay track_id repetidos para investigar después de la limpieza.')

track_id que aparecen más de 1 vez: 16641

Distribución de repeticiones:

   apariciones  nº de tracks
0            1         73099
1            2         11712
2            3          2984
3            4          1372
4            5           431
5            6           117
6            7            22
7            8             2
8            9             1

Ejemplo — track_id '6S3JlDAGk3uu3NtZbPnuhS' aparece 9 veces:

,track_id,track_name,artists,track_genre,popularity
8315,6S3JlDAGk3uu3NtZbPnuhS,Baby Blue - Remastered 2010,Badfinger,blues,67
19759,6S3JlDAGk3uu3NtZbPnuhS,Baby Blue - Remastered 2010,Badfinger,country,67
34728,6S3JlDAGk3uu3NtZbPnuhS,Baby Blue - Remastered 2010,Badfinger,folk,67
62226,6S3JlDAGk3uu3NtZbPnuhS,Baby Blue - Remastered 2010,Badfinger,j-pop,67
63087,6S3JlDAGk3uu3NtZbPnuhS,Baby Blue - Remastered 2010,Badfinger,j-rock,67
82064,6S3JlDAGk3uu3NtZbPnuhS,Baby Blue - Remastered 2010,Badfinger,power-pop,67
84129,6S3JlDAGk3uu3NtZbPnuhS,Baby Blue - Remastered 2010,Badfinger,psych-rock,67
99727,6S3JlDAGk3uu3NtZbPnuhS,Baby Blue - Remastered 2010,Badfinger,singer-songwriter,67
102732,6S3JlDAGk3uu3NtZbPnuhS,Baby Blue - Remastered 2010,Badfinger,songwriter,67

→ Conclusión: la misma canción aparece una vez por cada género en el que
  está clasificada en Spotify. Es la estructura del dataset, no un error.

Eliminamos duplicados exactos (filas idénticas si las hubiera)

In [21]:
df = df.drop_duplicates()

# Después, se eliminan los registros que tengan el identificador de canción ('track_id') repetido,
# manteniendo únicamente la primera aparición detectada (keep='first')

# df = df.drop_duplicates(subset=['track_id'], keep='first') 

# NO HAY QUE BORRARLOS SI ES LA ESTRUCTURA DEL DATASET Y NO UN ERROR

df

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,5,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,0,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,0,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,7,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,1,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

### PASO 4: Optimización y corrección de tipos de datos

In [30]:
# A) Convertir columnas de texto repetitivo a tipo 'category'
df.loc[:, 'track_genre'] = df['track_genre'].astype('category')
df.loc[:, 'key'] = df['key'].astype('category')
df.loc[:, 'mode'] = df['mode'].astype('category')
df.loc[:, 'time_signature'] = df['time_signature'].astype('category')

# B) Reducir enteros de 64 bits a tamaños más eficientes
df.loc[:, 'popularity'] = df['popularity'].astype('int8')     # Rango 0 a 100 cabe en int8
df.loc[:, 'duration_ms'] = df['duration_ms'].astype('int32')   # Duración cabe en int32

# C) Reducir flotantes de 64 bits a 32 bits (precisión suficiente)
columnas_flotantes = [
    'danceability', 'energy', 'loudness', 'speechiness', 
    'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo'
]
# Para modificar múltiples columnas a la vez con .loc, pasamos la lista de columnas
df.loc[:, columnas_flotantes] = df[columnas_flotantes].astype('float32')

# D) Convertir columnas 'object' (que son texto) a tipo 'string'
object_cols = df.select_dtypes(include='object').columns
df.loc[:, object_cols] = df[object_cols].astype('string')

### PASO 5: Verificación final del dataset limpio

Mostramos el resumen para comprobar el resultado de la limpieza y el ahorro de memoria

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 113549 entries, 0 to 113999
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   track_id          113549 non-null  string
 1   artists           113549 non-null  string
 2   album_name        113549 non-null  string
 3   track_name        113549 non-null  string
 4   popularity        113549 non-null  int8
 5   duration_ms       113549 non-null  int32
 6   explicit          113549 non-null  bool
 7   danceability      113549 non-null  float32
 8   energy            113549 non-null  float32
 9   key               113549 non-null  category
 10  loudness          113549 non-null  float32
 11  mode              113549 non-null  category
 12  speechiness       113549 non-null  float32
 13  acousticness      113549 non-null  float32
 14  instrumentalness  113549 non-null  float32
 15  liveness          113549 non-null  float32
 16  valence           113549 non-null  float32
 17  tempo             113549 non-null  float32
 18  time_signature    113549 non-null  category
 19  track_genre       113549 non-null  category
dtypes: bool(1), category(4), float32(9), int32(1), int8(1), string(4)
memory usage: 9.3 MB

### Paso 6: Guardar el dataset limpio en un archivo parquet

In [29]:
df.to_parquet('spotify_dataset_limpio.parquet')